# Generated by Django 6.0.1 on 2026-01-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_key',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
